/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LargeButton: typeof import('./src/components/LargeButton.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    MainSelect: typeof import('./src/components/MainSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Select.vue')['default']
  }
}
